export const heroSlidesData = [
	{
		id: 4664634,
		year: 2023,
		rating: '8.4',
		title: 'Оппенгеймер',
		genres: ['биография', 'драма', 'история'],
		image: '/assets/img-1.jpg',
	},
	{
		id: 1077781,
		year: 2023,
		rating: '7.7',
		title: 'Убийцы цветочной луны',
		genres: ['драма', 'кримминал', 'история'],
		image: '/assets/img-2.jpg',
	},
	{
		id: 1229684,
		year: 2023,
		rating: '7.7',
		title: 'Миссия невыполнима: Смертельная рассплата. Часть первая',
		genres: ['боевик', 'триллер', 'приключения'],
		image: '/assets/img-3.jpg',
	},
	{
		id: 1044280,
		year: 2023,
		rating: '7.9',
		title: 'Страж Галактики. Часть 3',
		genres: ['фантастика', 'боевик', 'комедия', 'приключения'],
		image: '/assets/img-4.jpg',
	},
	{
		id: 1219177,
		year: 2023,
		rating: '8.6',
		title: 'Человек-паук: Паутина вселенных',
		genres: ['мультфильм', 'фантастика', 'фэнтези', 'боевик', 'приключения', 'семейный'],
		image: '/assets/img-5.jpg',
	},
	{
		id: 1267348,
		year: 2023,
		rating: '7.7',
		title: 'Джон Уик 4',
		genres: ['боевик', 'триллер', 'кримминал'],
		image: '/assets/img-6.jpg',
	},
	{
		id: 4499386,
		year: 2023,
		rating: '8.0',
		title: 'Оставленные',
		genres: ['драма', 'комедия'],
		image: '/assets/img-7.jpg',
	},
	{
		id: 999881,
		year: 2023,
		rating: '7.2',
		title: 'Русалочка',
		genres: ['фэнтези', 'мелодрама', 'мюзикл'],
		image: '/assets/img-8.jpg',
	},
	{
		id: 5000997,
		year: 2023,
		rating: '7.4',
		title: 'Air: Большой прыжок',
		genres: ['драма', 'биография'],
		image: '/assets/img-9.jpg',
	},
	{
		id: 1013343,
		year: 2023,
		rating: '7.4',
		title: 'Вонка',
		genres: ['семейный', 'приключения', 'комедия', 'фэнтези', 'мюзикл'],
		image: '/assets/img-10.jpg',
	},
]